# Generated by Django 6.0.3 on 2026-03-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('tur', models.CharField(max_length=100)),
                ('puan', models.FloatField(default=0.0)),
                ('afis', models.ImageField(blank=True, null=True, upload_to='afisler/')),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
    ]
