# Generated by Django 6.0.3 on 2026-04-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazar', models.CharField(blank=True, max_length=200, null=True)),
                ('tur', models.CharField(blank=True, max_length=100, null=True)),
                ('sayfa_sayisi', models.IntegerField(blank=True, default=0, null=True)),
                ('ozet', models.TextField(blank=True, null=True)),
                ('kapak_resmi', models.ImageField(blank=True, null=True, upload_to='kitaplar/')),
            ],
        ),
    ]
