# Generated by Django 6.0.3 on 2026-04-18 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='kapak_resmi',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='ozet',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='sayfa_sayisi',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='tur',
        ),
        migrations.RemoveField(
            model_name='kitap',
            name='yazar',
        ),
        migrations.AddField(
            model_name='kitap',
            name='afis_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kitap',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitap',
            name='liste_durumu',
            field=models.CharField(choices=[('okumak_istediklerim', 'Okumak İstediklerim'), ('okuduklarim', 'Okuduklarım')], default='okumak_istediklerim', max_length=50),
        ),
        migrations.AddField(
            model_name='kitap',
            name='puan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kitap',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitap',
            name='baslik',
            field=models.CharField(max_length=255),
        ),
    ]
