# Generated by Django 6.0.3 on 2026-04-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('tur', models.CharField(blank=True, max_length=100, null=True)),
                ('sezon_sayisi', models.IntegerField(blank=True, default=1, null=True)),
                ('bolum_sayisi', models.IntegerField(blank=True, default=0, null=True)),
                ('puan', models.FloatField(blank=True, default=0.0, null=True)),
                ('afis', models.ImageField(blank=True, null=True, upload_to='dizi_afisler/')),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
