# Generated by Django 6.0.3 on 2026-04-18 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dizi',
            name='basim_yili',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dizi',
            name='bolum_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dizi',
            name='ozet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dizi',
            name='sezon_sayisi',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dizi',
            name='tur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dizi',
            name='yonetmen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Yaratıcı/Yönetmen'),
        ),
        migrations.AlterField(
            model_name='dizi',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dizi',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dizi',
            name='liste_durumu',
            field=models.CharField(choices=[('izlediklerim', 'İzlediğim Diziler'), ('izlemek_istediklerim', 'İzlemek İstediğim Diziler')], default='izlemek_istediklerim', max_length=30),
        ),
        migrations.CreateModel(
            name='DiziYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('kisisel_puan', models.IntegerField(default=5)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('dizi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='series.dizi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
