# Generated by Django 6.0.4 on 2026-04-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArkadashlikIstegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('kabul_edildi', 'Kabul Edildi'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_istekler', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_istekler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gonderen', 'alici')},
            },
        ),
    ]
