# Generated by Django 6.0.3 on 2026-04-18 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('tur', models.CharField(blank=True, max_length=100, null=True)),
                ('puan', models.FloatField(default=0.0)),
                ('afis_url', models.URLField(blank=True, max_length=500, null=True)),
                ('liste_durumu', models.CharField(choices=[('izlediklerim', 'İzlediğim Filmler'), ('izlemek_istediklerim', 'İzlemek İstediğim Filmler')], default='izlemek_istediklerim', max_length=30)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
