# Generated by Django 6.0.3 on 2026-04-18 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='basim_yili',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='ozet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='sayfa_sayisi',
            field=models.IntegerField(default=0, verbose_name='Süre (dk)'),
        ),
        migrations.AddField(
            model_name='film',
            name='yazar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Yönetmen/Oyuncular'),
        ),
        migrations.CreateModel(
            name='FilmYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('kisisel_puan', models.IntegerField(default=5)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='movies.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
